# SPDX-License-Identifier: MIT
name: Java build (no eclipse parts)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 17
    - name: "Gradle clean build"
      run: ./gradlew clean build

